Repository werds7890/phone_list, pull requests merged in 2023-09, with the labels that each got.

#2 [LITTLE_FIX] ContactAddUi
  app/src/main/java/com/example/phone_list/ContactAddFragment.kt
  app/src/main/res/layout/fragment_contact_add.xml
  app/src/main/res/values/strings.xml
Labels: UI

#7 Dialog/UI
  app/src/main/java/com/example/phone_list/ContactAddFragment.kt
  app/src/main/res/drawable/dialog_edit_text_style.xml
  app/src/main/res/drawable/dialog_user_img.png
  app/src/main/res/layout/add_dialog.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: UI

#8 [FEAT] : ⚙️ TabLayout 및 ViewPager2 적용
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/ViewPagerAdapter.kt
  app/src/main/res/layout/activity_main_contact.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#9 Detail/UI
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentAdapter.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentData.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/res/drawable/JS.jpg
  app/src/main/res/drawable/SH.jpg
  app/src/main/res/drawable/SY.jpg
  app/src/main/res/drawable/TY.jpg
  app/src/main/res/drawable/YA.jpg
  app/src/main/res/drawable/YR.jpg
  app/src/main/res/drawable/hy.jpg
  app/src/main/res/drawable/sn_1.jpg
  app/src/main/res/layout/contact_list_view.xml
Labels: Feature

#10 Main data move to ContactListFragment
  .idea/deploymentTargetDropDown.xml
  app/src/main/res/drawable/tp.jpg
Labels: Feature

#15 [LITTLE_FIX]연락처데이터, 디테일페이지로 데이터 받아오기(완)
  app/src/main/java/com/example/phone_list/ContactDetailFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentAdapter.kt
  app/src/main/res/layout/activity_main_contact.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/item_list.xml
Labels: Data Injection

#16 Add contact dialog/feature
  .idea/misc.xml
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/DataKey.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/ShowDialogFragment.kt
  app/src/main/java/com/example/phone_list/ViewPagerAdapter.kt
  app/src/main/res/drawable/floating_button_img48.png
  app/src/main/res/layout/activity_main_contact.xml
  app/src/main/res/layout/contact_list_view.xml
Labels: Feature

#17 [BUG_FIX] : 🐛 List 아이템 Dialog로 추가 시 새로운 Fragment가 생성되는 현상 수정, 아이템 추가 …
  app/build.gradle
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentData.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/ShowDialogFragment.kt
  app/src/main/res/layout/activity_main_contact.xml
  app/src/main/res/layout/contact_list_view.xml
Labels: bug

#18 [LITTLE_FIX] : 🔧 Dialog 아이템 추가 시 빈칸처리, Dialog 내부 버튼 테마색상으로 변경, item 글…
  app/build.gradle
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/ShowDialogFragment.kt
  app/src/main/java/com/example/phone_list/ViewPagerAdapter.kt
  app/src/main/res/drawable/fab_icon_24.png
  app/src/main/res/layout/add_dialog.xml
  app/src/main/res/layout/contact_list_view.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: UI

#20 [FEAT]디테일페이지 수정기능추가
  .idea/misc.xml
  app/src/main/java/com/example/phone_list/ContactDetailFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
Labels: Feature

#22 Mypage edit/feature
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/MyPageFragment.kt
  app/src/main/java/com/example/phone_list/MypageEditFragment.kt
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_mypage_edit.xml
Labels: Feature

#24 Viewtype/feature
  app/src/main/java/com/example/phone_list/ContactDetailFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentAdapter.kt
  app/src/main/java/com/example/phone_list/ItemViewType.kt
  app/src/main/java/com/example/phone_list/LayoutType.kt
  app/src/main/java/com/example/phone_list/MainContactActivity.kt
  app/src/main/java/com/example/phone_list/MyPageFragment.kt
  app/src/main/java/com/example/phone_list/ViewPagerAdapter.kt
  app/src/main/res/drawable/contact_add_round.xml
  app/src/main/res/drawable/style_btn_convert_layout.xml
  app/src/main/res/layout/activity_main_contact.xml
  app/src/main/res/layout/contact_list_view.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/item_list_grid.xml
  app/src/main/res/layout/item_list_left.xml
  app/src/main/res/menu/bottom_nav_menu.xml
  app/src/main/res/values/colors.xml
Labels: Feature

#25 [LITTLE_FIX]디테일페이지 이미지수정, 다이얼로그 이미지 수정중
  .idea/misc.xml
  app/build.gradle
  app/src/main/java/com/example/phone_list/ContactDetailFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentAdapter.kt
  app/src/main/java/com/example/phone_list/ContactListFragmentData.kt
  app/src/main/java/com/example/phone_list/ShowDialogFragment.kt
  app/src/main/res/drawable/oval.xml
  app/src/main/res/drawable/rectangle.xml
  app/src/main/res/drawable/sosi.jpg
  app/src/main/res/layout/add_dialog.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: bug

#26 [LITTLE_FIX]디테일페이지, 다이얼로그페이지 수정기능 완료
  app/src/main/java/com/example/phone_list/ContactListFragment.kt
  app/src/main/java/com/example/phone_list/ShowDialogFragment.kt
Labels: Feature

#28 [LITTLE_FIX] : 🔧 모든 글씨체 일치 완료
  app/src/main/res/layout/add_dialog.xml
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/item_list.xml
  app/src/main/res/layout/item_list_grid.xml
  app/src/main/res/layout/item_list_left.xml
Labels: UI

#29 [DESIGN]디자인,폰트 통일 및 전화걸기 추가
  app/src/main/java/com/example/phone_list/ContactDetailFragment.kt
  app/src/main/res/layout/fragment_contact_detail.xml
  app/src/main/res/layout/fragment_my_page.xml
Labels: UI, Feature

#31 최종
  app/src/main/res/layout/fragment_my_page.xml
Labels: final
